[package]
name = "dumpling-arena"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "dumpling-arena"
path = "src/main.rs"

[dependencies]
agent-avocado = { path = "../agent-avocado" }
agent-blueberry = { path = "../agent-blueberry" }
agent-cherry = { path = "../agent-cherry" }
agent-dumpling = { path = "../agent-dumpling" }
snipe-core = { path = "../snipe-core" }
snipe-prng = { path = "../snipe-prng" }
