[package]
name = "cherry-train"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "cherry-train"
path = "src/main.rs"

[dependencies]
agent-cherry = { path = "../agent-cherry", features = ["training"] }
agent-publisher = { path = "../agent-publisher" }
ctrlc = "3.4"
snipe-core = { path = "../snipe-core" }
snipe-prng = { path = "../snipe-prng" }
