[package]
name = "agent-honey"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
snipe-core = { path = "../snipe-core" }

[dev-dependencies]
agent-garlic = { path = "../agent-garlic" }
snipe-prng = { path = "../snipe-prng" }

[[bench]]
name = "mate_search"
harness = false
