[package]
name = "eel-train"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "eel-train"
path = "src/main.rs"

[dependencies]
agent-avocado = { path = "../agent-avocado" }
agent-cherry = { path = "../agent-cherry" }
agent-eel = { path = "../agent-eel", features = ["training"] }
snipe-core = { path = "../snipe-core" }
snipe-prng = { path = "../snipe-prng" }
