[workspace]
resolver = "2"
members = [
    "crates/snipe-core",
    "crates/snipe-prng",
    "crates/agent-avocado",
    "crates/agent-cherry",
    "crates/agent-fajita",
    "crates/agent-arena",
    "crates/agent-dumpling",
    "crates/dumpling-arena",
    "crates/cherry-train",
    "crates/fajita-train",
    "crates/snipe-wasm",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/kylejlin/snipe-hunt"
rust-version = "1.85"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true

[profile.profiling]
inherits = "release"
debug = true
strip = false
