[workspace]
resolver = "2"
members = [
    "crates/snipe-core",
    "crates/old-snipe-core",
    "crates/old-snipe-ai",
    "crates/old-snipe-banana",
    "crates/old-snipe-wasm",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/kylejlin/snipe-hunt"
rust-version = "1.85"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true

[profile.release.package.old-snipe-ai]
debug = 1
